# Generated by Django 4.2.4 on 2023-09-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('phone', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
